### ISSUE TITLE
Implement Prettier — Due by October 02, 2020

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/js-coding-standards#2]
https://make.wordpress.org/core/2019/12/09/proposed-javascript-coding-standards-revisions-for-prettier-compatibility/

**Comment by aubreypwd** [comment]
Need to read, and consider if this impacts our standards...

**Comment by gregrickaby** [comment]
I would very much like Prettier to be part of our workflow ASAP. We're burning through project budgets with back-and-forth code reviews over formatting. When an engineer saves a file, it should be re-formatted by a computer to match our standard. Then, the file can be linted for code quality. 

>... instantly formatted. This removes a distraction for contributors who write or review code, and allows them to focus on the more valuable aspects of their work...

https://prettier.io/docs/en/comparison.html 
and
https://prettier.io/docs/en/integrating-with-linters.html

**Comment by aubreypwd** [comment]
> Code editors should be able to auto-format on save (yes, this includes support for Prettier)

See https://github.com/WebDevStudios/wd_s/issues/548

**Comment by aubreypwd** [comment]
Got a prettier shared config built https://github.com/WebDevStudios/prettier-config-js-coding-standards and all I need to do is get it installed as a dependancy of `js-coding-standards` and do some testing....
